apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cfk-sc
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true