---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 100Gi
  metricReporter:
    enabled: true
  passwordEncoder:
    secretRef: password-encoder-secret
  storageClass:
    name: cfk-sc
  services:
    kafkaRest:
      authentication:
        type: basic
        basic:
          secretRef: credential
          roles:
            - Administrators