---
apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-poc-dest
  namespace: confluent
spec:
  name: clusterlink-poc
  sourceInitiatedLink:
    linkMode: Destination
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
  mirrorTopics:
    - name: basic-topic
---
apiVersion: platform.confluent.io/v1beta1
kind: ClusterLink
metadata:
  name: clusterlink-poc-source
  namespace: confluent
spec:
  name: clusterlink-poc
  sourceInitiatedLink:
    linkMode: Source
  destinationKafkaCluster:
    kafkaRestClassRef:
      name: krc-cloud
      namespace: confluent
    authentication:
      type: plain
      jaasConfigPassThrough:
        secretRef: jaasconfig-ccloud
    tls:
      enabled: true
      secretRef: ccloud-tls-certs
    bootstrapEndpoint: pkc-d3rr1.us-east-1.aws.confluent.cloud:9092
  sourceKafkaCluster:
    kafkaRestClassRef:
      name: krc-cfk
      namespace: confluent
    authentication:
      type: plain
      jaasConfig:
        secretRef: clrestcredential