apiVersion: platform.confluent.io/v1beta1
kind: SchemaExporter
metadata:
  name: cfk-schema-exporter
  namespace: confluent
spec:
  sourceCluster:
    schemaRegistryClusterRef:
      name: schemaregistry
      namespace: confluent
  destinationCluster:
    schemaRegistryRest:
      endpoint: https://psrc-d88yz.westeurope.azure.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: ccloud-sr-credentials
  subjects:
  - basic-topic-value
  contextName: .
  contextType: NONE