apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-cloud
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: https://pkc-d3rr1.us-east-1.aws.confluent.cloud:443
    kafkaClusterID: lkc-1jq7zv
    authentication:
      type: basic
      basic:
        secretRef: restclass-ccloud